'use strict';

(function () {
  window.ElementSelector = {
    BIG_CLOSE: '.big-picture__cancel',
    BIG_IMG: '.big-picture__img > img',
    BIG_PICTURE: '.big-picture',
    BODY: 'body',
    BUTTON: '__button',
    COMMENT_LOADER: '.comments-loader',
    COMMENTS_COUNT: '.comments-count',
    EDITOR_CLOSE: '.img-upload__cancel',
    EDITOR_FORM: '.img-upload__overlay',
    EFFECT_ITEM: '.effects__item',
    EFFECT_LEVEL: 'input[name="effect-level"]',
    EFFECT_LEVEL_DEPTH: '.effect-level__depth',
    EFFECT_LEVEL_LINE: '.effect-level__line',
    EFFECT_LEVEL_PIN: '.effect-level__pin',
    EFFECT_PREVIEW: 'effects__preview',
    ERROR: '.error',
    IMAGE_FILTER: '.effects__radio',
    IMAGE_PREVIEW: '.img-upload__preview > img',
    IMG_FILTERS: '.img-filters',
    IMG_FILTERS_ACTIVE: '.img-filters__button--active',
    LIKES_COUNT: '.likes-count',
    MAIN: 'main',
    PICTURE_COMMENT: '.picture__comments',
    PICTURE_IMG: '.picture__img',
    PICTURE_ITEM: '.picture',
    PICTURE_LIKES: '.picture__likes',
    PICTURE_TEMPLATE: '#picture',
    PICTURES: '.pictures',
    PREVIEW: '.img-upload__preview',
    PREVIEW_EFFECTS: '.effects__preview',
    PREVIEW_IMG: '.img-upload__preview img',
    SCALE_BIGGER: '.scale__control--bigger',
    SCALE_SMALLER: '.scale__control--smaller',
    SCALE_VALUE: '.scale__control--value',
    SLIDER: '.img-upload__effect-level',
    SOCIAL_CAPTION: '.social__caption',
    SOCIAL_COMMENT: '.social__comment',
    SOCIAL_COMMENT_COUNT: '.social__comment-count',
    SOCIAL_COMMENTS: '.social__comments',
    SOCIAL_PICTURE: '.social__picture',
    SOCIAL_TEXT: '.social__text',
    SUCCESS: '.success',
    UPLOAD_FILE: '#upload-file',
    UPLOAD_FORM: '#upload-select-image',
    VALIDATION_DESCRIPTION: '.text__description',
    VALIDATION_HASHTAGS: '.text__hashtags',
    VISUALLY_HIDDEN: '.visually-hidden',
    FILTER_DEFAULT_NAME: '#effect-none',
  };
  window.ElementClass = {
    COMMENT_FOCUS: 'social__footer-text',
    COMMENTS_CURRENT_COUNT: 'comments-count',
    COMMENTS_FULL_COUNT: 'comments-count',
    DESCRIPTION_FOCUS: 'text__description',
    EFFECT_PREVIEW: 'effects__preview',
    HASHTAGS_FOCUS: 'text__hashtags',
    HIDDEN: 'hidden',
    IMG_FILTERS_ACTIVE: 'img-filters__button--active',
    IMG_FILTERS_BUTTON: 'img-filters__button',
    IMG_FILTERS_INACTIIVE: 'img-filters--inactive',
    LOADER: 'comments-loader',
    MODAL_OPEN_CLASS: 'modal-open',
    PICTURE: 'picture',
    PICTURE_IMG: 'picture__img',
    VISUALLY_HIDDEN: 'visually-hidden',
    ERROR: 'error',
    SUCCESS: 'success',
  };
})();
